In [2]:
Strategy = {
    1:"QS",
    2:"ALS",
    3:"VS",
    4:"MR",
    5:"AO",
    6:"CG",
    7:"CC",
    8:"LC",
    9:"IT",
    10:"NA",
}

Curriculum_Area = {
    1:"read/lit",
    2:"math",
    3:"spell",
    4:"hand",
    5:"science",
    6:"soc sci",
    7:"health",
    8:"PE",
    9:"Music",
    10:"Art",
    11:"Lang",
    12:"Compos",
    13:"Non-ac",
    14:"ESL",
}

Physical_Group = {
    1:"TC",
    2:"LG",
    3:"SG",
    4:"Pairs",
    5:"Single",
}

Activity_Structure = {
    1:"lec/lis",
    2:"lec/per",
    3:"dir/lis",
    4:"dir/per",
    5:"dem/lis",
    6:"led/per",
    7:"ask/per",
    8:"ask/ans",
    9:"ans/ask",
    10:"ev/per",
    11:"obs/per",
    12:"ev/dis",
    13:"ev/cop",
    14:"obs/dis",
    15:"obs/cop",
    16:"NA/free",
    17:"NA/feed",
    18:"NA/tran",
    19:"NA/int",
    20:"NA/out",
    21:"interact",
}

Mode = {
    1:"writing",
    2:"reading",
    3:"aural",
    4:"verbal",
    5:"wr-re",
    6:"wr-au",
    7:"wr-ver",
    8:"re-wr",
    9:"re-au",
    10:"re-ver",
    11:"au-wr",
    12:"au-re",
    13:"ver-wr",
    14:"ver-re",
    15:"ver-au",
    16:"au-re-ver",
    17:"NA",
    18:"au-ver",
}

Language_Content = {
    1:"social",
    2:"academic",
    3:"light cog",
    4:"dns cog",
}

Lang_of_Instruction_Teacher = {
    1:"L1",
    2:"L2",
    3:"L1-2",
    4:"L2-1",
    5:"NA",
}

Lang_of_Instruction_Student = {
    1:"L1",
    2:"L2",
    3:"L1-2",
    4:"L2-1",
    5:"NA",
}

Protocol = {
    "Strategy":Strategy,
    "Curriculum_Area":Curriculum_Area,
    "Physical_Group":Physical_Group,
    "Activity_Structure":Activity_Structure,
    "Mode":Mode,
    "Language_Content":Language_Content,
    "Lang_of_Instruction_Teacher":Lang_of_Instruction_Teacher,
    "Lang_of_Instruction_Student":Lang_of_Instruction_Student,
}

In [3]:
import pandas as pd
import os

sheets = []
path = "/tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Codes"
for file in os.listdir(path):
    filename = os.fsdecode(file)
    if filename.endswith(".xlsx"): 
        file_p = os.path.join(path, filename)
        xl = pd.ExcelFile(file_p)
        df = xl.parse('Sheet1', skiprows=5, index_col=None, usecols=range(1,10))
        sheets.append(df)
main_df = pd.concat(sheets)
main_df.rename({'Lang of Instruction Teacher/Student': 'Lang of Instruction Teacher',
           'Unnamed: 9': 'Lang of Instruction Student'}, axis=1, inplace=True)
print(main_df.describe())

             Time    Strategy  Curriculum Area  Physical Group  \
count  600.000000  600.000000            600.0      600.000000   
mean    30.500000    4.750000             14.0        1.973333   
std     17.332552    3.346565              0.0        1.708065   
min      1.000000    1.000000             14.0        1.000000   
25%     15.750000    3.000000             14.0        1.000000   
50%     30.500000    3.000000             14.0        1.000000   
75%     45.250000   10.000000             14.0        1.250000   
max     60.000000   10.000000             14.0        5.000000   

       Activity Structure       Mode  Language Content  \
count          600.000000  600.00000        600.000000   
mean             9.470000   12.16000          3.690000   
std              6.367103    6.91598          0.744866   
min              1.000000    2.00000          1.000000   
25%              6.000000    3.00000          4.000000   
50%              8.000000   16.00000          4.000000   

In [68]:
import moviepy.editor as mp
from pathlib import Path

path = "/tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Videos"
output_path = "/tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios"
for file in os.listdir(path):
    filename = os.fsdecode(file)
    file_p = os.path.join(path, filename)
    find_ex = filename.rfind('.')
    name = filename[0:find_ex]
    clip = mp.VideoFileClip(file_p)
    clip.audio.write_audiofile(output_path + '/' + name + ".wav")


chunk:   0%|                                                                       | 0/54979 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Huang_ Cowboy Mouse Day 2-009.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/40352 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Huang_ Maisy Goes Camping Day 3.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/45246 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Huang_ Pete the cat Day 4-007.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/43354 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Huang_ Stop and go Day 1.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/42523 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Huang_ The princess and the pea-010.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/51197 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Lily_ Cowboy Mouse Day 2-005.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/47933 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Lily_ Maisy goes camping Day 3.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/45215 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Lily_ Pete the cat Day 4.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/46442 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Lily_ Stop and go Day 1.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/44271 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Lily_ The princess and the pea Day 4.wav


MoviePy - Done.


In [50]:
from pydub import AudioSegment
from pydub.utils import make_chunks

path = "/tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios"
output_path = "/tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Chunks"
for file in os.listdir(path):
    filename = os.fsdecode(file)
    file_p = os.path.join(path, filename)
    find_ex = filename.rfind('.')
    name = filename[0:find_ex]
    audio = AudioSegment.from_wav(file_p)
    twenty_seconds = 20 * 1000
    start_from_two_mins = audio[2*60*1000:22*60*1000]
    chunks = make_chunks(start_from_two_mins, twenty_seconds)
    for i, chunk in enumerate(chunks):
        temp_name = output_path + '/' + name + "[" + str(i) + "]" + ".wav"
        chunk.export(temp_name, format="wav")

In [25]:
import numpy
from scipy.io import wavfile

chunks_asarray = []
path = "/tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Chunks"

for file in os.listdir(path):
    filename = os.fsdecode(file)
    file_p = os.path.join(path, filename)
    fs, x = wavfile.read(file_p)
    x = numpy.array(x)
    chunks_asarray.append(x)

In [70]:
from sklearn.decomposition import PCA

decompo = []
for each in chunks_asarray: 
    pca = PCA(n_components=1,svd_solver='auto')
    pca.fit(each)
    newone = pca.singular_values_
    decompo.append(newone)

In [71]:
main_df["chunks"] = decompo

In [72]:
print(main_df["chunks"].head())

0     [5147701.080261368]
1     [5959836.193532026]
2     [4841757.367041219]
3    [4005632.3621220575]
4     [4253551.006842022]
Name: chunks, dtype: object


In [73]:
from sklearn.model_selection import train_test_split

X = main_df["chunks"].values
y = main_df["Lang of Instruction Teacher"].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [77]:
from sklearn.utils import check_consistent_length
print(X_train.shape,X_test.shape)
print(X_train)
print(X_test)
X_train_f = X_train.reshape(480, 1)
X_test_f = X_test.reshape(120, 1)
print(X_train_f.shape,X_test_f.shape)
print(X_train_f)
print(X_test_f)

(480,) (120,)
[array([4130902.12364178]) array([5249448.06332213])
 array([3336480.47537084]) array([5247837.8558853])
 array([3309897.14370343]) array([3405014.25324509])
 array([4248084.87982619]) array([4555157.08116136])
 array([1893040.56610099]) array([8294084.42298289])
 array([5524000.39883071]) array([4832785.45341025])
 array([2835111.37855088]) array([2659766.44598766])
 array([4750138.83506695]) array([1451850.36564392])
 array([4235339.4149793]) array([3423096.8129759])
 array([4437317.25255894]) array([4593462.24738684])
 array([4015124.47679332]) array([4163494.82774874])
 array([5451720.15990007]) array([3582387.21391937])
 array([4280124.37111159]) array([4855500.00999853])
 array([4918898.87349528]) array([6501386.89809544])
 array([3644147.94301328]) array([4137380.88465331])
 array([4139089.38107845]) array([3712012.04895087])
 array([4925457.7229377]) array([5215789.08581205])
 array([5514308.55936414]) array([4293485.38753535])
 array([5048788.64389412]) array([51

In [76]:
from sklearn.svm import SVC
reg = SVC(gamma='auto').fit(X_train_f, y_train)
reg.score(X_test_f, y_test)

0.6833333333333333