In [2]:
Strategy = {
    1:"QS",
    2:"ALS",
    3:"VS",
    4:"MR",
    5:"AO",
    6:"CG",
    7:"CC",
    8:"LC",
    9:"IT",
    10:"NA",
}

Curriculum_Area = {
    1:"read/lit",
    2:"math",
    3:"spell",
    4:"hand",
    5:"science",
    6:"soc sci",
    7:"health",
    8:"PE",
    9:"Music",
    10:"Art",
    11:"Lang",
    12:"Compos",
    13:"Non-ac",
    14:"ESL",
}

Physical_Group = {
    1:"TC",
    2:"LG",
    3:"SG",
    4:"Pairs",
    5:"Single",
}

Activity_Structure = {
    1:"lec/lis",
    2:"lec/per",
    3:"dir/lis",
    4:"dir/per",
    5:"dem/lis",
    6:"led/per",
    7:"ask/per",
    8:"ask/ans",
    9:"ans/ask",
    10:"ev/per",
    11:"obs/per",
    12:"ev/dis",
    13:"ev/cop",
    14:"obs/dis",
    15:"obs/cop",
    16:"NA/free",
    17:"NA/feed",
    18:"NA/tran",
    19:"NA/int",
    20:"NA/out",
    21:"interact",
}

Mode = {
    1:"writing",
    2:"reading",
    3:"aural",
    4:"verbal",
    5:"wr-re",
    6:"wr-au",
    7:"wr-ver",
    8:"re-wr",
    9:"re-au",
    10:"re-ver",
    11:"au-wr",
    12:"au-re",
    13:"ver-wr",
    14:"ver-re",
    15:"ver-au",
    16:"au-re-ver",
    17:"NA",
    18:"au-ver",
}

Language_Content = {
    1:"social",
    2:"academic",
    3:"light cog",
    4:"dns cog",
}

Lang_of_Instruction_Teacher = {
    1:"L1",
    2:"L2",
    3:"L1-2",
    4:"L2-1",
    5:"NA",
}

Lang_of_Instruction_Student = {
    1:"L1",
    2:"L2",
    3:"L1-2",
    4:"L2-1",
    5:"NA",
}

Protocol = {
    "Strategy":Strategy,
    "Curriculum_Area":Curriculum_Area,
    "Physical_Group":Physical_Group,
    "Activity_Structure":Activity_Structure,
    "Mode":Mode,
    "Language_Content":Language_Content,
    "Lang_of_Instruction_Teacher":Lang_of_Instruction_Teacher,
    "Lang_of_Instruction_Student":Lang_of_Instruction_Student,
}

In [3]:
import pandas as pd
import os

sheets = []
path = "/tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Codes"
for file in os.listdir(path):
    filename = os.fsdecode(file)
    if filename.endswith(".xlsx"): 
        file_p = os.path.join(path, filename)
        xl = pd.ExcelFile(file_p)
        df = xl.parse('Sheet1', skiprows=5, index_col=None, usecols=range(1,10))
        sheets.append(df)
main_df = pd.concat(sheets)
main_df.rename({'Lang of Instruction Teacher/Student': 'Lang of Instruction Teacher',
           'Unnamed: 9': 'Lang of Instruction Student'}, axis=1, inplace=True)
print(main_df.describe())

             Time    Strategy  Curriculum Area  Physical Group  \
count  600.000000  600.000000            600.0      600.000000   
mean    30.500000    4.750000             14.0        1.973333   
std     17.332552    3.346565              0.0        1.708065   
min      1.000000    1.000000             14.0        1.000000   
25%     15.750000    3.000000             14.0        1.000000   
50%     30.500000    3.000000             14.0        1.000000   
75%     45.250000   10.000000             14.0        1.250000   
max     60.000000   10.000000             14.0        5.000000   

       Activity Structure       Mode  Language Content  \
count          600.000000  600.00000        600.000000   
mean             9.470000   12.16000          3.690000   
std              6.367103    6.91598          0.744866   
min              1.000000    2.00000          1.000000   
25%              6.000000    3.00000          4.000000   
50%              8.000000   16.00000          4.000000   

In [68]:
import moviepy.editor as mp
from pathlib import Path

path = "/tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Videos"
output_path = "/tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios"
for file in os.listdir(path):
    filename = os.fsdecode(file)
    file_p = os.path.join(path, filename)
    find_ex = filename.rfind('.')
    name = filename[0:find_ex]
    clip = mp.VideoFileClip(file_p)
    clip.audio.write_audiofile(output_path + '/' + name + ".wav")


chunk:   0%|                                                                       | 0/54979 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Huang_ Cowboy Mouse Day 2-009.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/40352 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Huang_ Maisy Goes Camping Day 3.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/45246 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Huang_ Pete the cat Day 4-007.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/43354 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Huang_ Stop and go Day 1.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/42523 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Huang_ The princess and the pea-010.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/51197 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Lily_ Cowboy Mouse Day 2-005.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/47933 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Lily_ Maisy goes camping Day 3.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/45215 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Lily_ Pete the cat Day 4.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/46442 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Lily_ Stop and go Day 1.wav


MoviePy - Done.


chunk:   0%|                                                                       | 0/44271 [00:00<?, ?it/s, now=None]

MoviePy - Writing audio in /tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios/Lily_ The princess and the pea Day 4.wav


MoviePy - Done.


In [50]:
from pydub import AudioSegment
from pydub.utils import make_chunks

path = "/tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Audios"
output_path = "/tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Chunks"
for file in os.listdir(path):
    filename = os.fsdecode(file)
    file_p = os.path.join(path, filename)
    find_ex = filename.rfind('.')
    name = filename[0:find_ex]
    audio = AudioSegment.from_wav(file_p)
    twenty_seconds = 20 * 1000
    start_from_two_mins = audio[2*60*1000:22*60*1000]
    chunks = make_chunks(start_from_two_mins, twenty_seconds)
    for i, chunk in enumerate(chunks):
        temp_name = output_path + '/' + name + "[" + str(i) + "]" + ".wav"
        chunk.export(temp_name, format="wav")

In [25]:
import numpy
from scipy.io import wavfile

chunks_asarray = []
path = "/tamu_hw/csce_fall2021/csce606/ILOI/src/data/Beihai/Year 1/Chunks"

for file in os.listdir(path):
    filename = os.fsdecode(file)
    file_p = os.path.join(path, filename)
    fs, x = wavfile.read(file_p)
    x = numpy.array(x)
    chunks_asarray.append(x)

In [37]:
from sklearn.decomposition import PCA

decompo = []
for each in chunks_asarray: 
    pca = PCA(svd_solver='auto')
    pca.fit(each)
    newone = pca.singular_values_
    decompo.append(newone)

In [38]:
main_df["chunks"] = decompo

In [39]:
print(main_df["chunks"].head(20))

0     [5147701.080261255, 4238408.0668615475]
1      [5959836.193531979, 4350485.171641455]
2     [4841757.367041007, 3910841.9608996063]
3      [4005632.362121994, 3467131.311659885]
4     [4253551.006841975, 3305676.6375371423]
5     [5271505.644365246, 4117792.4109581327]
6     [4302648.602806017, 3152755.5417438024]
7     [4599794.306308122, 3591826.6487772623]
8      [5205396.480282859, 4038226.251929938]
9      [4824200.550002554, 3530168.654816658]
10     [4699578.998904272, 3708524.858541359]
11     [4670022.30648177, 3675600.9988357774]
12     [4468734.641761419, 3480997.201089258]
13     [4410727.120278566, 3234427.169038146]
14     [5490950.180038989, 4139770.239681063]
15    [5246796.229205225, 3951531.4235910815]
16     [4497184.003347504, 3011533.559629772]
17    [4486275.854757719, 3281464.5334746856]
18    [5237055.208546028, 3731872.5450278083]
19    [5093298.278303854, 4024309.0008143266]
Name: chunks, dtype: object


In [48]:
from sklearn.model_selection import train_test_split

X = main_df["chunks"].values
y = main_df["Lang of Instruction Teacher"].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [49]:
from sklearn.utils import check_consistent_length
print(X_train.shape,y_train.shape)
print()
print(X_train)
print()
print(y_train)
X_train = numpy.concatenate(X_train)
y_train = numpy.concatenate(y_train)
X_train = X_train.reshape(-1, 1)
y_train = y_train.reshape(-1, 1)

(480,) (480,)

[array([4130902.12364177, 3260839.77305807])
 array([5249448.0633222 , 4068963.16571466])
 array([3336480.4753709 , 2558382.15037859])
 array([5247837.85588512, 4162479.28706979])
 array([3309897.14370342, 2076359.13596514])
 array([3405014.25324508, 2272564.11414265])
 array([4248084.87982611, 3381656.24607259])
 array([4555157.08116141, 3752083.57773697])
 array([1893040.56610099, 1346079.47033594])
 array([8294084.42298272, 3871393.83864274])
 array([5524000.39883071, 4053855.50466824])
 array([4832785.45341016, 3628635.94373907])
 array([2835111.37855097, 2016357.61377934])
 array([2659766.44598765, 1680872.31407096])
 array([4750138.83506693, 3610773.57688621])
 array([1451850.36564392, 1015248.88864876])
 array([4235339.41497936, 2659073.22820923])
 array([3423096.81297585, 2866780.83998391])
 array([4437317.25255891, 2516671.75457548])
 array([4593462.24738687, 3407328.97635186])
 array([4015124.47679328, 3548733.38130884])
 array([4163494.82774878, 2887732.972851

ValueError: zero-dimensional arrays cannot be concatenated

In [50]:
from sklearn.svm import SVC
reg = SVC(gamma='auto').fit(X_train, y_train)
reg.score(X_test, y_test)

ValueError: Expected 2D array, got 1D array instead:
array=[4130902.12364177 3260839.77305807 5249448.0633222  4068963.16571466
 3336480.4753709  2558382.15037859 5247837.85588512 4162479.28706979
 3309897.14370342 2076359.13596514 3405014.25324508 2272564.11414265
 4248084.87982611 3381656.24607259 4555157.08116141 3752083.57773697
 1893040.56610099 1346079.47033594 8294084.42298272 3871393.83864274
 5524000.39883071 4053855.50466824 4832785.45341016 3628635.94373907
 2835111.37855097 2016357.61377934 2659766.44598765 1680872.31407096
 4750138.83506693 3610773.57688621 1451850.36564392 1015248.88864876
 4235339.41497936 2659073.22820923 3423096.81297585 2866780.83998391
 4437317.25255891 2516671.75457548 4593462.24738687 3407328.97635186
 4015124.47679328 3548733.38130884 4163494.82774878 2887732.97285116
 5451720.15989996 4849520.94167882 3582387.21391922 2667947.87592214
 4280124.37111162 3187858.40633219 4855500.00999855 3608311.63748485
 4918898.87349519 3989894.76419755 6501386.89809537 4380868.32636337
 3644147.94301317 2341008.75590048 4137380.88465335 3604447.04329393
 4139089.38107845 2939022.86465089 3712012.04895084 3016368.66401464
 4925457.7229378  3378100.46374569 5215789.08581208 4020954.7985548
 5514308.55936422 4152915.17107848 4293485.38753516 2624859.10029247
 5048788.64389415 3364336.21897554 5147701.08026125 4238408.06686155
 5388764.83378039 3717912.62311324 5024976.1606754  3954787.43143349
 2592858.2364311  2307081.86559795 4691957.76180219 3976338.22419567
 6107571.94857818 4256743.0249906  4930963.52599968 4299100.35580478
 4467732.06734697 3122901.90731047 3539291.17423372 2438590.41270228
 4033066.03005757 2674427.83319459 4197891.81096801 2807164.19455345
 4110640.15393819 2667448.46246062 3842408.00801655 2490984.58269054
 4528961.40524055 3779355.03645457 3882926.20605815 2912814.92334045
 4924297.99718688 3781678.10899528 4210974.88850293 3361881.33415822
 2365801.58041951 1443463.9357818  4087155.25859182 3349044.01233278
 5482415.57163693 3978475.93051294 3894415.6611205  2999590.04225723
 2525318.03884739 1690539.94286696 5155278.030026   4151172.70797187
 3764734.14271063 2590694.61181364 2230985.15997467 1529373.54228958
 3213820.2051968  2225300.9638209  3586661.10236276 2952537.17296048
 3302121.46835719 2617446.61419938 4580037.10076401 3261368.0877753
 5570355.68659135 4193718.01184301 6384543.61970631 4648012.95670208
 4401739.69548552 3396059.41338228 2392115.48431715 1823156.31881316
 3312011.34098081 2561844.37899123 4430368.7052805  3576375.59129269
 3278094.72646807 2463058.48157723 4516846.8549455  3710453.88339342
 5237055.20854603 3731872.54502781 4676562.8643741  3738146.79795254
 3585710.52842772 2568741.73999096 3028978.26458532 2117772.01471644
 4741690.83354438 3258519.67894476 3740610.84754716 2372961.69673119
 4938049.35978762 4231739.79131541 2833390.93326647 1903551.3722215
 4508079.63102179 2985270.64927569 3331866.62147895 2052029.43576246
 4030903.67728644 3255743.42708642 2342338.12168157 1744104.24220386
 4071062.7433694  2868781.80115264 3884371.31617047 2551741.22484714
 5755577.42281632 4537861.191548   3195372.5683843  1939559.61771431
 3073269.01255982 2316340.29590906 5056279.13430139 4192746.17420809
 3092971.011246   1899336.4045385  3554254.3722589  2696648.46105667
 4378009.60088681 3164404.178522   3257575.28032265 2619949.10955368
 2362079.2101567  1619692.82641654 3965035.74091979 2822723.4415073
 4282754.12216316 3358761.81597782 4007981.50715982 2971751.40855471
 3631471.39502203 2497003.85249994 3997544.70995638 2538925.61306621
 5695922.13830407 3850276.6522161  5877262.32387008 4499001.61942991
 5170493.78666483 3840490.35075527 3537107.30698941 2741926.77837234
 3934817.90767974 2844974.96898599 4745039.12845071 3329260.3315571
 3873555.94691195 2761035.16605397 3161771.7433964  2061704.83900534
 4599794.30630812 3591826.64877726 9199264.07136221 3622602.26795113
 4172762.35907383 2442678.19066979 5089964.63023799 3617457.61271782
 4363997.23232776 3308779.02106986 2127881.28093738 1350129.51584358
 4067651.73659297 3081155.3776883  5320887.56888322 4139794.89905519
 4742774.24500687 4015687.91164638 5634745.29509094 4187834.81435723
 3988377.31145549 3037641.65086673 4969880.50265098 4195645.78653399
 5145409.05379246 4533089.16709012 4576351.69757417 3760550.34856607
 4960405.07177045 3742473.72581124 5326489.48272964 4461239.31686737
 4470601.60900113 3361295.78093371 4288123.64944596 3168996.8430938
 4079352.10921582 2664386.88964114 4813168.93656007 2625345.86893425
 4082633.32775792 3137501.11503381 3098589.78083651 1966209.48462783
 3557772.91985179 2305783.64492731 2033482.40405472 1306540.41957625
 9380058.13363219 3860974.05366697 3277062.87590409 2001434.78819605
 4366844.26670287 3602292.48511922 4071121.99543224 3165601.44852539
 4912246.88147032 3702887.39005339 2388146.05790751 1411423.07739986
 4280834.26737245 3414367.80424323 3680001.22716117 2641431.0618805
 4763547.01508861 3516329.54542089 3203247.11920873 2282657.50232138
 4532518.43480216 3759777.92739991 4252910.80145672 2932224.00872055
 4680571.78160659 3432165.30435784 6198386.82785168 5190149.77143838
 3554154.82857209 2532164.32494555 4137552.271498   3270162.86911436
 5365783.05908381 4406700.47903529 3209286.49653234 2567116.24653565
 5701488.14342333 4783099.63354164 4542041.93469099 3359226.73241314
 2515833.38374579 1925188.12708633 2670581.6272508  1316595.71979407
 4657942.88547483 3650301.28085732 4496960.08907516 3384766.83036816
 7924686.24958326 4143608.60950435 6064774.74457721 4671865.49696705
 3079429.58285289 2234599.8992344  4525902.81890266 3604761.10667706
 4253551.00684198 3305676.63753714 8386586.20872945 5001109.24656211
 5503166.87290534 4382780.77420197 9225762.87184583 3072769.30616845
 4653093.80184541 3447185.6251589  5271505.64436525 4117792.41095813
 4534224.30818581 3675122.2313142  4280828.99002062 2543876.50838912
 3745885.59247541 3159384.46678996 3206758.8102524  2030415.0523161
 2209115.55578285 1573380.62706664 6138922.21900087 4597743.59220953
 3205074.62495448 2674519.46401761 3619129.8474225  2985134.54769998
 4734349.77976673 2438228.65434264 5927337.992151   4948908.78490413
 2632997.63999243 1501991.18004736 4470443.35522539 3713760.95744247
 3158892.29480927 2487348.498206   3099105.80962637 2570012.54569517
 4459551.16689343 3786369.60063512 6073917.10422267 4771142.29741403
 3991681.27522307 2984850.5659864  2871879.81443496 2122951.94971943
 2577554.65872691 1680802.18168764 3497906.58244889 3144582.5197269
 3813033.44860082 2407352.96938014 3645482.01059212 2463777.07772425
 5478701.26721926 4361370.82215372 4378944.52152391 3302167.56970666
 6251096.76790487 4592201.68471018 4224502.19569262 2965952.1845103
 4438986.34126768 2924158.39476416 4233883.24456729 3179459.93117984
 2536630.58142026 1980938.84691553 3843851.60398161 2789696.78523109
 2794784.54227325 1879998.79354964 4823194.14601408 4008172.33742218
 8071909.44301024 4568046.39915248 4683864.03525193 3635493.66425701
 5296909.69968955 4314991.87935557 3824138.63032908 2468708.75705579
 4285460.27815425 3143747.53490685 4789542.52883213 3750655.36429516
 2860031.34134268 2007474.9760839  4750917.62854009 3877258.57539593
 3920380.50025107 2930693.28607472 4040623.51974239 3155803.1332831
 4623961.83208084 3198060.05442307 3912778.13353587 2827242.45090029
 4375118.52963324 3197355.56445269 4967437.14149824 4246306.7588988
 1918209.49977136 1529684.75669374 4866046.5911419  3645332.14178433
 2949672.4958736  2183237.95149926 4513632.7179623  3121198.94589962
 6455288.9949759  2581283.89894156 3379607.57085447 2333045.89860472
 4833605.5465929  3206854.46291251 5112482.02966171 3941644.98258225
 4841757.36704101 3910841.96089961 4010378.67611875 2884793.30573849
 4172625.24346245 3530738.96429839 1848770.93727755 1239206.41957833
 3235857.520625   2857388.40062977 3296505.82742782 2611691.63174792
 4628991.42223712 3774469.80463684 3562138.39465046 2254627.28069891
 4103815.45551377 3036038.7162844  4890911.8623929  4273110.82477655
 2381686.25325898 1498818.47537846 3973111.53145936 2745403.75525662
 4425327.38722539 3262874.37130403 4667915.43881143 3478885.62777747
 3642828.84693778 2392508.65297549 4641516.95381559 3444093.57195882
 3294816.10565385 2176371.53166204 4332282.35904919 2973043.44441005
 3983998.13758442 2924273.60269544 3073690.82379795 2150253.88030175
 6362333.5981284  4197602.77912323 3403209.23527775 2867969.46618547
 5727196.07058372 4469637.59540728 4347801.17811987 3417681.83744681
 7153111.48163774 5212237.39710857 4553098.38369237 3134719.18122312
 5046818.60755241 3801359.72368656 4160599.90989723 3138288.62922958
 4996138.95875466 3769365.06162525 5063907.4367247  4021341.44568539
 4478671.1125569  3554060.41332104 5757838.1020898  4091100.74586501
 5132180.43688774 4589457.74783521 3269765.20632703 2330578.86558823
 3882819.29771491 3473645.23064541 3545388.69382024 2364253.8411905
 3539908.6335607  2690982.98369364 3829498.65811729 2877299.43408535
 4749778.54657532 3773501.1511291  5645085.29709928 4149780.7127229
 5132210.24330416 3739096.98486731 3339966.23865598 2223215.29457591
 4481468.8344673  3405002.11537099 4321835.33715261 3118842.88662615
 3804360.04179414 2685726.44019792 4491624.63427889 3187964.72062145
 2783284.18616529 1910252.72176178 3213008.37574374 2776250.12724419
 4305952.30537046 3519450.61295547 4392626.11345514 3733230.06469292
 4811309.63172403 3587664.62697579 3679743.93294437 2588524.33796952
 4998946.08768337 4197965.10769706 3300561.81838559 2362709.15898206
 4806953.47241162 3264078.36082163 5726729.51198911 4513463.34560939
 4278703.25713304 3090390.32211707 3752174.1307558  2988780.68085966
 4728993.65247757 3520654.90849298 4731052.37314922 3589305.93267411
 4537626.17250344 3162790.25365135 2850368.64705998 1877574.63059922
 5075383.42203091 4457107.40397425 3277263.28623092 2345019.7702749
 3404612.12745657 2359811.22845303 2327786.22791545 1928390.09870412
 3567348.59838697 2623350.29215909 4981396.67877507 4194674.42857045
 4131550.80921893 3204623.05347381 3966852.0018822  2727926.95670113
 3789087.54529795 2200878.18449508 4069421.89570697 3340870.36729947
 4515964.96592036 3841180.95391264 5352830.8312984  4674669.9759735
 4873651.24315635 3578996.24953617 2738522.37567341 1897882.78896178
 2982432.86118515 2030880.18778893 4326446.39308725 3399331.27935148
 4016185.62802086 2742079.40616877 3784644.94317408 3114812.83820647
 4897349.10087392 4026056.54632438 3586188.11290475 2200989.93635759
 3099064.95837546 2152808.2644968  7733374.20453113 3021285.53160737
 4302256.15856393 3433213.71214834 4562696.8910409  3830166.96679233
 2375277.54445323 1539049.46535824 3296729.84548431 2204633.75204127
 4160636.541805   3308850.21939924 3832633.59866922 2796752.04696151
 4525019.43623986 3883556.4828066  4555623.3591567  3989130.57898088
 4434199.18338674 3283435.26403051 4422486.18895789 3788745.78001159
 3431251.72095856 2517463.49089653 4720078.432571   3638739.53105895
 4011015.4155941  2963165.1484338  8895867.21612902 3963290.97363034
 2885337.13642666 1759480.04415639 4410727.12027857 3234427.16903815
 3388509.02551041 2552246.37923819 6395594.31512708 4663271.362226
 3408666.95475041 2341575.27679428 5335402.57984959 4291118.09327266
 3918247.53325901 3053986.17876678 5658552.45726366 3753297.4682137
 4388770.18017496 3200608.29067922 2143786.10291613 1642983.38730759
 4373804.71614686 3633137.95465219 2790163.98327248 1855650.19625581
 5342756.53581125 4477897.6912454  3898006.89966319 2615334.07484722
 9249876.81335038 4198676.10508593 4979676.86252154 3677464.13250198
 4862202.36009697 3677276.40423943 3726075.36999512 2619503.83701056
 2353337.02592031 1872237.14702941 6865734.71971119 5056665.44734287
 3791189.84995134 3240932.04324719 4497184.0033475  3011533.55962977
 6107377.25933895 4708509.21468669 4549499.27884839 2955453.06171115
 4272032.7759399  3197656.73136321 4562683.23145045 3374727.0112569
 6316449.15524154 3193871.70782448 3586623.16860458 2376943.03398658
 2557636.19002561 2113738.60884489 5184578.88646575 3544723.54651196
 3974307.42899554 2878149.5934922  3522585.5353781  2099661.35918104
 3025049.42277301 1924718.29869371 4363476.18063091 3441747.33851897
 4563512.20929599 2659241.5196652  5444076.9682224  4019136.4510655
 2248547.39131182 1672133.6908244  3599435.52759262 2861205.94136962
 5646399.36601743 4381497.29041339 5447859.01489072 4129327.18380666
 3828802.36277492 2455352.34389048 3554565.12895257 2597284.3721583
 5093298.27830385 4024309.00081433 3897881.45820611 2520248.32378783
 4268131.47245337 3443021.01826811 3765693.1876967  2637380.54461962
 3315460.68079897 2631049.83881738 6272478.84163835 4671036.50101465
 4648744.14460339 3886889.24189266 5282645.92319219 4499557.34517372
 4005632.36212199 3467131.31165989 5494035.45546379 4407641.05259686
 3594588.47811824 2875120.27765386 1854756.41016576  917233.00003993
 3200396.96601412 2027336.08012966 4181233.21272413 3122557.31077234
 2633858.02315481 1715551.15300491 2902559.00863637 1980695.40970868
 3705036.95322146 2342010.20662761 6492764.08960474 4491573.13971902
 5331252.99055864 4300037.09643079 4413554.85366559 2986843.06550959
 4820414.80130733 4073392.04311028 3400750.90627232 2774437.75330417
 4635418.18252829 3522808.68835939 5504391.04610004 4077148.7575853
 4426212.48893295 3164637.60966106 4638008.20886088 3726912.26821564
 3895512.35379313 2431113.82366322 3652072.43643917 2840316.330542
 4670022.30648177 3675600.99883578 6311492.51388139 4269854.19563986
 5275343.40901576 4090658.62793979 5188624.54924149 4144860.5674505
 4180422.29603645 2971474.96011916 5325522.06728517 4642930.57238056
 3901373.27773225 2972918.18469259 6849238.9047955  5270765.19135721
 4639869.15004028 3638889.43684357 3984819.51699452 3448205.94276189
 3811061.36285669 2898019.60894128 5241212.44401553 4578004.59701509
 4115706.12649643 2811492.81877909 2093507.76909244 1237867.75134488
 4623381.8450368  3381758.43086938 4578738.86772222 2964794.73076697
 4258191.16687486 3122485.16780173 4338523.12897548 3182006.39905697
 5105379.11299045 3565537.55514429 3381605.15875818 2318864.56565561
 4558732.42813702 2924198.29857257 4561636.92991215 2870564.36794636
 2901995.24993412 2225519.07130324 3665088.92435373 2673310.67005073
 5039012.19878133 3759352.70380133 5229129.13854369 4636916.05282248
 2303757.35602781 1499477.33413244 4449365.92734146 4005854.60227752
 5122223.57087313 3502687.27542417 5085268.04448525 2725863.09243551
 4836055.42946795 3549398.0070517  5050586.5816694  4318107.43227335
 4631113.75648746 3218635.23157495 4368470.97073246 3353037.63704341
 4552492.65026637 3396955.62879158 4200139.47933711 3118759.62469125
 2956018.07774967 2019848.04351945 3829779.18975976 3259054.94889187
 3747051.04455848 2653626.99306447 5309864.06145237 4072093.52978003
 4570720.23873958 3821933.14577601 4649109.40871246 3571673.52031799
 3564102.48380548 2328550.89899475 3442606.91348357 2635738.84379391
 5124271.28766477 4523763.70364583 4615110.70445697 3442245.60699262
 2489765.00053716 1500128.66709451 2976661.83404246 2226330.33664197
 7304775.74197562 5515006.9576513  4919099.72973494 3890549.90634679
 4642130.84680594 3153240.34142117 5497916.578268   4181670.55251689
 4343082.67150342 3769213.89833602 4537207.87903889 3317173.55230094
 3831348.23531153 2556708.64258592 4521687.88912793 3678163.01540417
 2315913.6160649  1653420.0116493  2763932.50251068 2383786.42505176
 4366465.26373593 3478471.20006971 4861674.7031914  3484365.5612644
 5354362.60731602 4044974.29978547 4342849.76891151 3005656.89424718
 3936196.12906379 3280138.82895057 4158736.25724533 3366881.99048108
 2257022.82152593 1597931.72655778 2584754.76257882 1895064.24874759
 4510039.74611647 3564363.52559218 4208052.82866206 3110627.41614161
 4017957.98435847 3176664.71012533 4537832.93086063 3981921.46877542
 4631960.80257663 3542681.53517172 5028702.34209177 4385993.93187275
 3653414.89800918 2504758.02008079 6448159.77379863 4861434.86558056
 4911610.35516523 4088891.33371177 4692237.6981275  3932978.9027655
 3444830.81837783 2458869.85169406 4960181.28315714 4011573.65141936
 5214508.33907899 4217779.48424321 2109151.60922864 1530290.11641237
 5150301.76450496 3529117.36892303 3237281.19407694 2168983.26632444
 4588625.90895298 3174474.9485395  9161466.05070989 3403345.36388061
 4847572.76523874 3866326.95148777 2559852.17357268 1630242.13614113
 4824200.55000255 3530168.65481666 6322008.86148621 4802722.77128192
 4741247.45362693 3784920.5285187  2682811.85621545 1865767.59117307].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.